name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Move to intended folder
      run: | 
        cd /home/runner/work/test-simulator/test-simulator/file_cpp
        dir
      
    - name: Install dependencies + Run check
      run: | 
        cd /home/runner/work/test-simulator/test-simulator/file_cpp
        make
        make check
